### ISSUE TITLE
`srclib-javascript` processes coffeescript file and crashes

### ISSUE THREAD

**Issue by MaikuMori** [sourcegraph/srclib-javascript#11]
If I recall the file which caused the crash is [this one](https://github.com/MaikuMori/sourcegraph-atom/blob/get-it-running/lib/sourcegraph-atom.coffee). I'll add more details tomorrow if needed.

Command run + output:

```
src api list --file "/home/maiku/Projects/sourcegraph-atom/lib/sourcegraph-atom.coffee": Running: [/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-go/.bin/srclib-go scan --repo github.com/MaikuMori/sourcegraph-atom --subdir .] --> with input {} warning: "./..." matched no packages Running: [/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript scan-commonjs --repo github.com/MaikuMori/sourcegraph-atom --subdir .] --> with input {} Running: [/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python scan --repo github.com/MaikuMori/sourcegraph-atom --subdir .] --> with input {} File "/usr/bin/pydep-run.py", line 54 print json.dumps(setup_infos) ^ SyntaxError: invalid syntax EOF Running: [/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-ruby/.bin/srclib-ruby scan --repo github.com/MaikuMori/sourcegraph-atom --subdir .] --> with input {} SCANNERS (4) - sourcegraph.com/sourcegraph/srclib-go scan - sourcegraph.com/sourcegraph/srclib-javascript scan-commonjs - sourcegraph.com/sourcegraph/srclib-python scan - sourcegraph.com/sourcegraph/srclib-ruby scan SOURCE UNITS (1) - CommonJSPackage: sourcegraph-atom CONFIG PROPERTIES (0) /home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:206 if (commonJSPackage.Files.length == 0) { ^ TypeError: Cannot read property 'length' of undefined at graph (/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:206:34) at ReadStream.<anonymous> (/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:264:9) at ReadStream.emit (events.js:129:20) at _stream_readable.js:908:16 at process._tickCallback (node.js:355:11) exit status 1 EOF .srclib-cache/7b351445a87feb9862e8980e3775a495e7f9aebd/sourcegraph-atom/CommonJSPackage.graph.json: command failed: src tool --methods program "sourcegraph.com/sourcegraph/srclib-javascript" "graph" < .srclib-cache/7b351445a87feb9862e8980e3775a495e7f9aebd/sourcegraph-atom/CommonJSPackage.unit.json | src internal normalize-graph-data --unit-type "CommonJSPackage" --dir . 1> .srclib-cache/7b351445a87feb9862e8980e3775a495e7f9aebd/sourcegraph-atom/CommonJSPackage.graph.json (exit status 1) command failed: src tool --methods program "sourcegraph.com/sourcegraph/srclib-javascript" "graph" < .srclib-cache/7b351445a87feb9862e8980e3775a495e7f9aebd/sourcegraph-atom/CommonJSPackage.unit.json | src internal normalize-graph-data --unit-type "CommonJSPackage" --dir . 1> .srclib-cache/7b351445a87feb9862e8980e3775a495e7f9aebd/sourcegraph-atom/CommonJSPackage.graph.json (exit status 1)
```

And if we extract just the error:
```
sourcegraph-atom CONFIG PROPERTIES (0) /home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:206 if (commonJSPackage.Files.length == 0) { ^ TypeError: Cannot read property 'length' of undefined at graph (/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:206:34) at ReadStream.<anonymous> (/home/maiku/.srclib/sourcegraph.com/sourcegraph/srclib-javascript/.bin/srclib-javascript:264:9) at ReadStream.emit (events.js:129:20) at _stream_readable.js:908:16 at process._tickCallback (node.js:355:11) exit status 1 EOF
```

It points to this file: https://github.com/sourcegraph/srclib-javascript/blob/master/.bin/srclib-javascript#L206

**Comment by MaikuMori** [comment]
@samertm can you look into this?
